# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/alex/GitHub/parametric_qam/ip_repo/edit_qam_mod_v1_0.cache/wt [current_project]
set_property parent.project_path /home/alex/GitHub/parametric_qam/ip_repo/edit_qam_mod_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zedboard:part0:1.0 [current_project]
set_property ip_repo_paths /home/alex/GitHub/parametric_qam/ip_repo/qam_mod_1.0 [current_project]
set_property ip_output_repo /home/alex/GitHub/parametric_qam/ip_repo/edit_qam_mod_v1_0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/alex/GitHub/parametric_qam/ip_repo/qam_mod_1.0/src/qam_8.v
  /home/alex/GitHub/parametric_qam/ip_repo/qam_mod_1.0/src/qam_4.v
  /home/alex/GitHub/parametric_qam/ip_repo/qam_mod_1.0/src/qam_2.v
  /home/alex/GitHub/parametric_qam/ip_repo/qam_mod_1.0/src/qam_top.v
  /home/alex/GitHub/parametric_qam/ip_repo/qam_mod_1.0/hdl/qam_mod_v1_0_S00_AXI.v
  /home/alex/GitHub/parametric_qam/ip_repo/qam_mod_1.0/hdl/qam_mod_v1_0_S00_AXIS.v
  /home/alex/GitHub/parametric_qam/ip_repo/qam_mod_1.0/hdl/qam_mod_v1_0_M00_AXIS.v
  /home/alex/GitHub/parametric_qam/ip_repo/qam_mod_1.0/hdl/qam_mod_v1_0.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top qam_mod_v1_0 -part xc7z020clg484-1


write_checkpoint -force -noxdef qam_mod_v1_0.dcp

catch { report_utilization -file qam_mod_v1_0_utilization_synth.rpt -pb qam_mod_v1_0_utilization_synth.pb }
